### ISSUE TITLE
Moving a tearout card over Bitflux causes judder

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#528]
Moving the tearout card around the place is fine and smooth, but if it goes over the Bitflux chart, it starts juddering a bit.

Edit: Experimentation -- Seems to be related to number of days loaded on the chart

**Comment by WPFerg** [comment]
it's the pointer events over Bitflux. I set:
```css
div#showcase-container * {
    pointer-events: none;
}
```
and it was smooth.
